SENSOR_NAMES = {
    "active_power_incoming"  : "Wirkleistung Bezug",
    "active_energy_incoming" : "Wirkenergie Bezug",
    "apparent_power_incoming" : "Scheinleistung Bezug",
    "apparent_energy_incoming" : "Scheinenergie Bezug",
    "apparent_power_outgoing" : "Scheinleistung Einspeisung",
    "apparent_energy_outgoing" : "Scheinenergie Einspeisung ",
    "reactive_power_outgoing" : "Blindleistung Einspeisung",
    "reactive_energy_outgoing" : "Blindenergie Einspeisung",
    "reactive_power_incoming" : "Blindleistung Bezug",
    "reactive_energy_incoming" : "Blindenergie Bezug",
    "power_factor" : "Leistungsfaktor",
    "supply_frequency" : "Netzfrequenz",
    "active_power_outgoing" : "Wirkleistung Einspeisung",
    "active_energy_outgoing" : "Wirkenergie Einspeisung",
    "active_power_incoming_l1" : "Wirkleistung Bezug (L1)",
    "active_energy_incoming_l1" : "Wirkenergie Bezug (L1)",
    "active_power_outgoing_l1" : "Wirkleistung Einspeisung (L1)",
    "active_energy_outgoing_l1" : "Wirkenergie Einspeisung (L1)",
    "reactive_power_incoming_l1" : "Blindleistung Bezug (L1)",
    "reactive_energy_incoming_l1" : "Blindenergie Bezug (L1)",
    "reactive_power_outgoing_l1" : "Blindleistung Einspeisung (L1)",
    "reactive_energy_outgoing_l1" : "Blindenergie Einspeisung (L1)",
    "apparent_power_incoming_l1" : "Scheinleistung Bezug (L1)",
    "apparent_energy_incoming_l1" : "Scheinenergie Bezug (L1)",
    "apparent_power_outgoing_l1" : "Blindleistung Einspeisung (L1)",
    "apparent_energy_outgoing_l1" : "Blindenergie Einspeisung (L1)",
    "current_l1" : "Stromstärke (L1)",
    "voltage_l1" : "Spannung (L1)",
    "power_factor_l1" : "Leistungsfaktor (L1)",
    "active_power_incoming_l2" : "Wirkleistung Bezug (L2)",
    "active_energy_incoming_l2" : "Wirkenergie Bezug (L2)",
    "active_power_outgoing_l2" : "Wirkleistung Einspeisung (L2)",
    "active_energy_outgoing_l2" : "Wirkenergie Einspeisung (L2)",
    "reactive_power_incoming_l2" : "Blindleistung Bezug (L2)",
    "reactive_energy_incoming_l2" : "Blindenergie Bezug (L2)",
    "reactive_power_outgoing_l2" : "Blindleistung Einspeisung (L2)",
    "reactive_energy_outgoing_l2" : "Blindenergie Einspeisung (L2)",
    "apparent_power_incoming_l2" : "Scheinleistung Bezug (L2)",
    "apparent_energy_incoming_l2" : "Scheinenergie Bezug (L2)",
    "apparent_power_outgoing_l2" : "Blindleistung Einspeisung (L2)",
    "apparent_energy_outgoing_l2" : "Blindenergie Einspeisung (L2)",
    "current_l2" : "Stromstärke (L2)",
    "voltage_l2" : "Spannung (L2)",
    "power_factor_l2" : "Leistungsfaktor (L2)",
    "active_power_incoming_l3" : "Wirkleistung Bezug (L3)",
    "active_energy_incoming_l3" : "Wirkenergie Bezug (L3)",
    "active_power_outgoing_l3" : "Wirkleistung Einspeisung (L3)",
    "active_energy_outgoing_l3" : "Wirkenergie Einspeisung (L3)",
    "reactive_power_incoming_l3" : "Blindleistung Bezug (L3)",
    "reactive_energy_incoming_l3" : "Blindenergie Bezug (L3)",
    "reactive_power_outgoing_l3" : "Blindleistung Einspeisung (L3)",
    "reactive_energy_outgoing_l3" : "Blindenergie Einspeisung (L3)",
    "apparent_power_incoming_l3" : "Scheinleistung Bezug (L3)",
    "apparent_energy_incoming_l3" : "Scheinenergie Bezug (L3)",
    "apparent_power_outgoing_l3" : "Blindleistung Einspeisung (L3)",
    "apparent_energy_outgoing_l3" : "Blindenergie Einspeisung (L3)",
    "current_l3" : "Stromstärke (L3)",
    "voltage_l3" : "Spannung (L3)",
    "power_factor_l3" : "Leistungsfaktor (L3)"
    }
