SENSOR_NAMES = {
    "active_power_incoming"  : "Active power+",
    "active_energy_incoming" : "Active energy+",
    "apparent_power_incoming" : "Apparent power+",
    "apparent_energy_incoming" : "Apparent energy+",
    "apparent_power_outgoing" : "Apparent power-",
    "apparent_energy_outgoing" : "Apparent energy-",
    "reactive_power_outgoing" : "Reactive power-",
    "reactive_energy_outgoing" : "Reactive energy-",
    "reactive_power_incoming" : "Reactive power+",
    "reactive_energy_incoming" : "Reactive energy+",
    "power_factor" : "Power factor",
    "supply_frequency" : "Supply frequency",
    "active_power_outgoing" : "Active power-",
    "active_energy_outgoing" : "Active energy-",
    "active_power_incoming_l1" : "Active power+ (L1)",
    "active_energy_incoming_l1" : "Active energy+ (L1)",
    "active_power_outgoing_l1" : "Active power- (L1)",
    "active_energy_outgoing_l1" : "Active energy- (L1)",
    "reactive_power_incoming_l1" : "Reactive power+ (L1)",
    "reactive_energy_incoming_l1" : "Reactive energy+ (L1)",
    "reactive_power_outgoing_l1" : "Reactive power- (L1)",
    "reactive_energy_outgoing_l1" : "Reactive energy- (L1)",
    "apparent_power_incoming_l1" : "Apparent power+ (L1)",
    "apparent_energy_incoming_l1" : "Apparent energy+ (L1)",
    "apparent_power_outgoing_l1" : "Reactive power- (L1)",
    "apparent_energy_outgoing_l1" : "Reactive energy- (L1)",
    "current_l1" : "Current (L1)",
    "voltage_l1" : "Voltage (L1)",
    "power_factor_l1" : "Power factor (L1)",
    "active_power_incoming_l2" : "Active power+ (L2)",
    "active_energy_incoming_l2" : "Active energy+ (L2)",
    "active_power_outgoing_l2" : "Active power- (L2)",
    "active_energy_outgoing_l2" : "Active energy- (L2)",
    "reactive_power_incoming_l2" : "Reactive power+ (L2)",
    "reactive_energy_incoming_l2" : "Reactive energy+ (L2)",
    "reactive_power_outgoing_l2" : "Reactive power- (L2)",
    "reactive_energy_outgoing_l2" : "Reactive energy- (L2)",
    "apparent_power_incoming_l2" : "Apparent power+ (L2)",
    "apparent_energy_incoming_l2" : "Apparent energy+ (L2)",
    "apparent_power_outgoing_l2" : "Reactive power- (L2)",
    "apparent_energy_outgoing_l2" : "Reactive energy- (L2)",
    "current_l2" : "Current (L2)",
    "voltage_l2" : "Voltage (L2)",
    "power_factor_l2" : "Power factor (L2)",
    "active_power_incoming_l3" : "Active power+ (L3)",
    "active_energy_incoming_l3" : "Active energy+ (L3)",
    "active_power_outgoing_l3" : "Active power- (L3)",
    "active_energy_outgoing_l3" : "Active energy- (L3)",
    "reactive_power_incoming_l3" : "Reactive power+ (L3)",
    "reactive_energy_incoming_l3" : "Reactive energy+ (L3)",
    "reactive_power_outgoing_l3" : "Reactive power- (L3)",
    "reactive_energy_outgoing_l3" : "Reactive energy- (L3)",
    "apparent_power_incoming_l3" : "Apparent power+ (L3)",
    "apparent_energy_incoming_l3" : "Apparent energy+ (L3)",
    "apparent_power_outgoing_l3" : "Reactive power- (L3)",
    "apparent_energy_outgoing_l3" : "Reactive energy- (L3)",
    "current_l3" : "Current (L3)",
    "voltage_l3" : "Voltage (L3)",
    "power_factor_l3" : "Power factor (L3)"
    }
